server:
    port: 8999

eureka:
    instance:
        hostname: localhost

spring:
    application:
        name: api-gateway
    cloud:
        gateway:
            routes:
            - id: net-calculator
              uri: lb://net-calculator
              predicates:
                - Path=/nc/**
            - id: tax-rate-provider
              uri: lb://tax-rate-provider
              predicates:
                - Path=/tr/** 